[build]
  command = "echo 'VITE_API_URL='$VITE_API_URL && rm -rf dist node_modules/.vite && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://camg-bopp.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
